export default {
  LOAD_PRODUCTS: 'LOAD_PRODUCTS',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  ADD_PRODUCT: 'ADD_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',

  LOAD_PRODUCT: 'LOAD_PRODUCT',
  LOAD_PRODUCTS_ERROR: 'LOAD_PRODUCTS_ERROR',

  ADD_PRODUCTS_TO_CART: 'ADD_PRODUCTS_TO_CART',
  LOAD_CART_PRODUCT: 'LOAD_CART_PRODUCT',
  DELETE_CART_PRODUCT: 'DELETE_CART_PRODUCT',
  LOAD_CART_PRODUCT_ERROR: 'LOAD_CART_PRODUCT_ERROR',
  DECREASE_PRODUCT: 'DECREASE_PRODUCT',
  DECREASE_PRODUCT_ERROR: 'DECREASE_PRODUCT_ERROR',

  POST_LOGIN: 'POST_LOGIN',
  POST_ERROR_LOGIN: 'POST_ERROR_LOGIN'
};
