export default {
  LOAD_PRODUCTS: 'LOAD_PRODUCTS',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  ADD_PRODUCT: 'ADD_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',

  LOAD_PRODUCT: 'LOAD_PRODUCT',

  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT'
};
